server:
  port: 8090
  use-forward-headers: true
  undertow:
    io-threads: 2
    worker-threads: 36
    buffer-size: 1024
    directBuffers: true
  servlet:
    session:
      timeout: 86400s

jasypt:
  encryptor:
    password: lyblog

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2database 配置
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/lyblog/lyblog
#    username: admin
#    password: 123456

    #MySql配置
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.244.9.82:3306/ly_blog?characterEncoding=utf8&useSSL=false
    username: root
    password: ENC(g0m9sjWJzpj7tMHc43UqF04RqO+c25oh)

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
      auto_import: /spring.ftl as spring
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 多语言资源文件路径
  messages:
    basename: i18n/messages
logging:
  file: ./logs/log.log

